MUME/MMapper

build.sh, src/display/mapcanvas.cpp, src/display/mapcanvas.h, src/display/mapwindow.cpp
=> Retina and general high DPI monitor support for MMapper

src/proxy/proxy.cpp
Applying @tomaswindsor 's fix in comment https://github.com/MUME/MMapper/commit/299b87b7ad596f1b3e75b2852f40589809e5dba7#commitcomment-17658501
=> Fixing TCP keep alive in Linux

src/configuration/configuration.cpp, src/mapdata/roomfactory.cpp, src/parser/abstractparser.cpp, src/parser/abstractparser.h, src/parser/mumexmlparser.cpp
Enhance offline mode with regard to prompts and ANSI color  
Also disable old rooms using dark/lit info from prompt
We will need to do this until we have:
1) Day/night cycle detection
2) Blindness detection
This reverts a feature in #38
=> Offline mode enhancement and dark/lit bugfix

src/configuration/configuration.cpp, src/configuration/configuration.h, src/display/mapcanvas.cpp, src/preferences/generalpage.cpp, src/preferences/generalpage.h, src/preferences/generalpage.ui
* Antialiasing and trilinear filtering now default to off
=> Support for trilinear filtering

src/display/mapcanvas.cpp, src/display/mapcanvas.h
Implements support for  #17
This PR makes steps to support OpenGL 3.1 by replacing some deprecated API calls
=>  Distant player's location is now hinted 

src/parser/mumexmlparser.cpp, src/parser/mumexmlparser.h
Fixes https://github.com/MUME/MMapper/issues/64
=> XML tags can now be displayed if desired

CMakeLists.QtIOCompressor.in, CMakeLists.txt, src/CMakeLists.txt
Fixes https://github.com/MUME/MMapper/issues/82
=> Build QtIOCompressor into MMapper by default

src/display/mapcanvas.cpp, src/mainwindow/roomeditattrdlg.cpp, src/mapdata/mmapper2exit.h, src/parser/abstractparser.cpp, src/parser/abstractparser.h
* These exit flags are colored as:
* cyan --> `damage` and `fall`
* yellow --> `guarded`
This implements issues #70 and #69
=> Introduce `damage`, `fall`, and `guarded` exit flags

src/CMakeLists.txt, src/configuration/configuration.cpp, src/configuration/configuration.h, src/mainwindow/mainwindow.cpp, src/preferences/generalpage.cpp, src/preferences/generalpage.h, src/preferences/generalpage.ui, src/proxy/connectionlistener.cpp, src/proxy/connectionlistener.h, src/proxy/mumesocket.cpp, src/proxy/mumesocket.h, src/proxy/proxy.cpp, src/proxy/proxy.h, src/proxy/telnetfilter.cpp, src/proxy/telnetfilter.h
Support for SSL encryption directly to MUME
=> SSL encryption support

src/client/ctelnet.h, src/display/mapcanvas.cpp, src/mainwindow/mainwindow.cpp, src/mainwindow/mainwindow.h, src/parser/abstractparser.h
First attempt at https://github.com/MUME/MMapper/issues/123
=> Cleaning up actions in MainWindow

.travis.yml
Release builds are on using Catalina and Xcode 11.2
=> Bump Travis CI to Xcode to 11.2

src/opengl/legacy/impl_gl20.cpp
This reverts commit fe1df7a9a8ad1f9cfb4d865fbeeac6092c5e80aa.
=> Revert "Enable polygon smoothing"

.appveyor.yml
=> Upgrade AppVeyor CI pipeline

src/CMakeLists.txt, src/display/InfoMarkSelection.cpp, src/display/InfoMarkSelection.h, src/display/mapcanvas.cpp, src/mapdata/enums.cpp, src/mapdata/enums.h, src/mapdata/infomark.h, src/parser/AbstractParser-Actions.cpp, src/parser/AbstractParser-Commands.cpp, src/parser/AbstractParser-Commands.h, src/parser/AbstractParser-Mark.cpp, src/parser/AbstractParser-Room.cpp, src/parser/abstractparser.cpp, src/parser/abstractparser.h, src/proxy/proxy.cpp, src/syntax/Value.cpp, src/syntax/Value.h
add, update, or remove first text infomark without mouse
=> add _infomark command

src/CMakeLists.txt, src/configuration/configuration.cpp, src/configuration/configuration.h, src/global/QuotedQString.h, src/global/TaggedString.h, src/mainwindow/mainwindow.cpp, src/mainwindow/mainwindow.h, src/pandoragroup/CGroupChar.cpp, src/proxy/GmcpMessage.h, src/proxy/GmcpModule.h, src/proxy/MudTelnet.cpp, src/proxy/connectionlistener.cpp, src/proxy/connectionlistener.h, src/proxy/proxy.cpp, src/proxy/proxy.h, src/roompanel/RoomManager.cpp, src/roompanel/RoomManager.h, src/roompanel/RoomMob.cpp, src/roompanel/RoomMob.h, src/roompanel/RoomMobs.cpp, src/roompanel/RoomMobs.h, src/roompanel/RoomWidget.cpp, src/roompanel/RoomWidget.h
Fixes #238 - implement "Room Panel" showing GMCP messages Room.Chars.* i.e. show in a new dedicated panel
the list of mobs/players in current room and who they are fighting
=> Add "Room Panel" feature

src/clock/mumeclock.cpp
Added a couple of dawn/dusk messages that the game sends when a player is around warrens.
=> Added warrens dawn/dusk messages

src/pandoragroup/mmapper2character.h, src/pandoragroup/mmapper2group.cpp, src/pandoragroup/mmapper2group.h, src/parser/AbstractParser-Actions.cpp
Also fixes Fighting position bug introduced in 6f1baeed2fd10517f0f49ba4d1136dddf9d47c5e
=> use Char.Vitals position field

.github/workflows/build-test.yml
=> fix windows msvc build

.gitignore, src/timers/CTimers.h, tests/CMakeLists.txt, tests/TestCTimers.cpp, tests/TestCTimers.h
Hey, here are some tests for timer functionality as my first PR to this repo.
=> Timer tests

.gitignore, src/display/Infomarks.cpp, tests/CMakeLists.txt, tests/TestCTimers.cpp, tests/roompanel/TestRoomManager.cpp, tests/roompanel/TestRoomManager.h, tests/roompanel/TestRoomMob.cpp, tests/roompanel/TestRoomMob.h, tests/roompanel/TestRoomMobs.cpp, tests/roompanel/TestRoomMobs.h
Testing pipeline with a simple change because pipeline kept failing
=> Room Manager Tests 2(Testing pipeline)
