MUME/MMapper

- NEWS.txt
- src/display/mapcanvas.cpp
When a special exit is present, 2.3.6 (and maybe others) set the default color for walls to be drawn after the special exit to 'white'.
It should have been 'black'. 
This bug fix it. I wasn't able to trace back where the bug was introduced, it may have been a side effect of another change, likely when High DPI screen support was added.
(There still is another bug where the stipple colors are lost, but it is independent, and I have not yet figured it out)
I have based this PR on top of PR#22 (there only dependency is the bump in version). I can rebase if needed.
> Fix wall color when special exit is present

- src/mapdata/mapdata.cpp
- src/mapdata/mapdata.h
- src/parser/abstractparser.cpp
- src/parser/abstractparser.h
This adds two new commands: _note to set a note in the current room, and _pnote to print the current note.
Also makes _pdynamic and _pstatic work; they'd previously bitrotted to print nothing.
> Command line access to set and print note

- src/CMakeLists.txt
- src/mainwindow/findroomsdlg.cpp
- src/mapdata/mapdata.cpp
- src/mapdata/mapdata.h
- src/mapdata/mmapper2exit.cpp
- src/mapdata/mmapper2exit.h
- src/mapdata/roomfilter.cpp
- src/mapdata/roomfilter.h
- src/mapdata/shortestpath.cpp
- src/mapdata/shortestpath.h
- src/mapfrontend/mapfrontend.h
- src/mapstorage/basemapsavefilter.cpp
- src/parser/abstractparser.cpp
- src/parser/abstractparser.h
Adds a new command, _dirs, that prints the shortest path to rooms satisfying a condition.
By default it searches the room name, but different flags can give different options.  The format is
`_dirs [-(name|desc|note|exits|all)] search pattern`.
For example,
```
>_dirs caras
Distance 19.45: The Gates of Caras Galadhon
dirs: e3n4e2ne
Distance 20.05: Before the Walls of Caras Galadhon
dirs: e3n2ene3n2e
>_dirs -a ferry
Distance 14.9: Landing in the Forest
dirs: 2en3ese
Distance 64.75: A Landing
dirs: 2s6e
Distance 586.45: Road to Standelf
dirs: nwn6ws3wn6w2s4wsw2sw3s8ws9wn4w11nwn2wu8wsw3de3dn8ws8wswsw2usds3wn3wnws3wu6wswnwnwnwnwn6ws5w2sw4s3wsws2ws3wsws4wsws3ws3wsws4ws2wswsws10ws2wn6wn2wn6wsws4wnwnwnwn3wnw2n9ws3w4s4w2s2ws2ws6wnwnwnwnwnw2n2e2n2w2ne10nwnwnwnwnwn2wnwnw2nwnwnwnwn3wnwn3wn7wn2wn2w2nw …
```
> Shortest path directions

- src/display/mapcanvas.cpp
- src/mapdata/mapdata.h
- src/parser/abstractparser.cpp
- src/parser/abstractparser.h
Adds a `_search` function similar `_dirs`, except it highlights matching rooms rather than prints directions to them.  I'm not quite sure why selected things are highlighted in red -- maybe it was intended to debug leaks? -- but it seems to work ok.
Addresses #5 (just `_search -n note text`).
> Search function

- CMakeLists.txt
- NEWS.txt
- src/display/mapcanvas.cpp
- src/display/mapcanvas.h
- src/mainwindow/infomarkseditdlg.h
- src/mainwindow/roomeditattrdlg.cpp
- src/mainwindow/roomeditattrdlg.h
- src/mainwindow/roomeditattrdlg.ui
- src/mapdata/mmapper2exit.h
- src/mapstorage/mapstorage.cpp
- src/mapstorage/mapstorage.h
- src/mapstorage/olddoor.h
I extended the exit flag with a 'river flow' that allows to store the direction of the flow of a river.
With this info, I display a path for the river flow, so that this is not a surprise for the player.
Here is how it looks like:
(Screenshot also show use of  colored and rotated info mark ;-) (It is in a previous PR)
> Store and display river flow direction

- src/mapdata/shortestpath.cpp
The old code stored a pointer into the QVector sp_nodes, which could be invalid after elements are added.  This could occasionally cause segmentation faults.
> Fix occasional segfaults in _dirs

- src/expandoracommon/mmapper2event.cpp
- src/mainwindow/findroomsdlg.h
- src/mapdata/roomfactory.cpp
- src/parser/abstractparser.cpp
- src/parser/abstractparser.h
If your prompt has:
* `*` or `!` or `)` means lit
* `o` means dark
This PR begins support for #38
> Room lighting in prompts now updates older maps

- src/configuration/configuration.cpp
- src/display/mapcanvas.cpp
- src/preferences/parserpage.cpp
* Map background now changes without restart
* Room name / description 'ERROR' squished
* Cleaned up old force patterns settings that weren't relevant for XML
>  Improved configuration panel usability 

- src/configuration/configuration.cpp
- src/configuration/configuration.h
- src/display/mapcanvas.cpp
- src/mapdata/mapdata.h
- src/preferences/generalpage.cpp
- src/preferences/generalpage.h
- src/preferences/generalpage.ui
Anti-aliasing is now enabled by default. You can disable it in the settings.
Also included are fixes to a bunch of OpenGL regressions from the Qt5 migration. This might fix the issue in #28 because I am unable to reproduce the problem.
> Multisample anti-aliasing support

- src/CMakeLists.txt
- src/clock/mumeclock.cpp
- src/clock/mumeclock.h
- src/clock/mumeclockwidget.cpp
- src/clock/mumeclockwidget.h
- src/clock/mumeclockwidget.ui
- src/clock/mumemoment.cpp
- src/clock/mumemoment.h
- src/configuration/configuration.cpp
- src/configuration/configuration.h
- src/mainwindow/mainwindow.cpp
- src/mainwindow/mainwindow.h
- src/parser/abstractparser.cpp
- src/parser/abstractparser.h
- src/parser/mumexmlparser.cpp
- src/parser/mumexmlparser.h
- src/parser/parserutils.cpp
- src/parser/patterns.cpp
- src/preferences/generalpage.cpp
- src/preferences/generalpage.h
- src/preferences/generalpage.ui
- src/proxy/connectionlistener.cpp
- src/proxy/connectionlistener.h
- src/proxy/proxy.cpp
- src/proxy/proxy.h
- src/tests/CMakeLists.txt
- src/tests/testclock.cpp
- src/tests/testclock.h
- src/tests/testparser.cpp
- src/tests/testparser.h
This add support for Issue #44 and supports all races. MMapper will be very cautious in the beginning of the game because MUME has Clock skew over time. It will only show the time when it is certain enough that the time it has is correct.
> MMapper now has a built in Mume clock

- src/display/mapcanvas.cpp
- src/expandoracommon/mmapper2event.cpp
- src/expandoracommon/mmapper2event.h
- src/mainwindow/roomeditattrdlg.cpp
- src/mainwindow/roomeditattrdlg.h
- src/mainwindow/roomeditattrdlg.ui
- src/mapdata/mmapper2exit.h
- src/mapdata/mmapper2room.cpp
- src/mapdata/mmapper2room.h
- src/mapdata/roomfactory.cpp
- src/mapstorage/jsonmapstorage.cpp
- src/mapstorage/mapstorage.cpp
- src/parser/abstractparser.cpp
- src/parser/abstractparser.h
- src/parser/mumexmlparser.cpp
- src/pathmachine/pathmachine.cpp
- src/pathmachine/pathmachine.h
- src/preferences/parserpage.cpp
- src/preferences/parserpage.ui
- src/proxy/proxy.cpp
Trolls and orcs are now able to map sunlit rooms using exits like \*north\*. Trolls can do this at night as well because they can detect outdoor rooms exit flags like ^south^.
Other new features:
* `_trollexit` command to toggle Troll exit mapping manually
* Dark rooms are differentiated from troll safe sunlit rooms by amount of darkness
*Note: Mapper mode needs to be enabled for this to work*
This PR provides some additional features as part of #38 as per discussion with @tomaswindsor
> Troll exit automapping for directly and indirectly sunlit rooms

- src/configuration/configuration.cpp
- src/configuration/configuration.h
- src/display/mapcanvas.cpp
- src/display/mapcanvas.h
- src/mainwindow/roomeditattrdlg.cpp
- src/mapdata/mmapper2exit.h
- src/mapstorage/mapstorage.cpp
- src/preferences/generalpage.cpp
- src/preferences/generalpage.h
- src/preferences/generalpage.ui
Adds support for #41 and #40
No match exits are a bit spammy on the default map so I've added a configuration item to disable their rendering.
> Display more exits flags on map and introduce the NO_FLEE flag

- src/parser/abstractparser.cpp
- src/parser/abstractparser.h
- src/parser/mumexmlparser.cpp
Players can also mark rooms of interest manually with the `_markcurrent` command.
Implements support for https://github.com/MUME/MMapper/issues/42
> The room where the player has died will be automatically highlighted

- src/clock/mumeclock.cpp
- src/clock/mumeclock.h
- src/parser/abstractparser.cpp
- src/parser/mumexmlparser.cpp
- src/parser/patterns.cpp
- src/parser/patterns.h
- src/tests/testclock.cpp
- src/tests/testclock.h
I noticed that the clock would unsync when it saw snow on the ground or if the clouds cleared up. I'm going to limit the sync to only known weather strings now.
> MumeClock syncs only on known weather

- src/parser/mumexmlparser.cpp
- src/parser/mumexmlparser.h
Mw+ can now `/snoop` characters and watch them on MMapper with only some slight hiccups.
> Minimal <snoop> tag support

- CMakeLists.txt
- src/CMakeLists.txt
- src/mainwindow/aboutdialog.cpp
- src/mainwindow/mainwindow.cpp
- src/mapstorage/abstractmapstorage.cpp
- src/mapstorage/abstractmapstorage.h
- src/mapstorage/jsonmapstorage.cpp
- src/mapstorage/jsonmapstorage.h
- src/mapstorage/mapstorage.cpp
- src/mapstorage/mapstorage.h
QtIOCompressor causes a lot of headaches and with Qt6 on the horizon I would rather not have it around if possible.
Let's migrate to the native `qCompress` and `qUncompress` methods which have better support.
> Migrate away from QtIOCompressor for new saves

- src/clock/mumeclock.cpp
- tests/testclock.cpp
MUME updated the `time` and `look clock` output and we need to update the regular expressions to match.
> Updating time and clock strings

- src/client/ctelnet.cpp
- src/client/ctelnet.h
- src/client/stackedinputwidget.cpp
- src/proxy/mumesocket.cpp
- src/proxy/proxy.cpp
This PR provides minimal [RFC 2066](https://tools.ietf.org/html/rfc2066) support for MMapper's built in client. Once MUME supports this standard it should be easier for the clients and mappers to know what the character encoding that is currently in use is.
On connection start for all clients:
-
MUME sends:  `IAC DO CHARSET`
Client sends either: 
- `IAC WILL CHARSET` if it supports RFC 2066
- `IAC WONT CHARSET` if it does not (or will not respond)
MUME sends:  `IAC SB CHARSET REQUEST DELIM NAMES IAC SE`
- DELIM is any character that does not appear in the charset name or IAC (eg. comma, space)
- NAME:  the [IANA character set](https://www.iana.org/assignments/character-sets/character-sets.xml) string (eg. `UTF-8`, `LATIN1`, `US-ASCII`)
Client sends:  `IAC SB CHARSET ACCEPTED NAME IAC SE` …
> Character encoding auto detection for the built in client

- src/mapdata/roomfactory.cpp
Climb exits introduced in commit https://github.com/MUME/MMapper/commit/5005e3727993a61caf5d1b92668cf76e87b3214b#diff-79e49887935fd1521dbb826cc9556ab1 added 4th ExitFlags bit and a bug.
This bug most likely explains the proliferation of NO_MATCH exits on older maps. We'll need to clean that up in another PR.
> Fix ExitFlags bits offset

- src/parser/abstractparser.cpp
- src/parser/abstractparser.h
- src/parser/mumexmlparser.cpp
- src/parser/mumexmlparser.h
Normalize strings by removing Latin-1 characters or stripping ANSI only for room names, static descriptions, and dynamic descriptions.
As a side effect, exits now preserve their color from MUME.
https://github.com/MUME/MMapper/issues/122
> Do not normalize all strings from MUME

- .snapcraft.yaml
- appdata/CMakeLists.txt
- appdata/org.mume.MMapper.appdata.xml
- src/CMakeLists.txt
- src/org.mume.MMapper.desktop
This is necessary for flatpak packaging that requires all applications
to use a unique reverse-DNS based identifier.
http://docs.flatpak.org/en/latest/conventions.html#application-ids
> Rename appdata, desktop file and icons to use reverse-DNS name

- src/global/enums.h
src/mapdata/../global/enums.h:55:24: error: 'runtime_error' is not a member of 'std'
> Include missing header to fix the build with gcc 10

- src/org.mume.MMapper.desktop
This helps gnome-shell map the app window to the desktop file (so that
correct icon and name are shown).
> Add StartupWMClass to desktop file

- .appveyor.yml
Ubuntu 20.04 is unable to install 18.04 .debs due to miniupnpc
> Switch deb from Ubuntu 18.04 to Debian Buster

- src/parser/abstractparser.cpp
_dirs gives  a summary of directions, like so:
```
*.>_dirs Pasture-Land
Distance 1.5: Rolling Pasture-Land
dirs: s (total: n)
Distance 4.5: Pasture-Land
dirs: 2ws (total: 2w n)
```
The n/s summary is flipped.  This fixes it.
> total: in _dirs had n/s switched

- .gitignore
- src/CMakeLists.txt
- src/mainwindow/mainwindow.cpp
- src/mainwindow/mainwindow.h
- src/mapstorage/XmlMapStorage.cpp
- src/mapstorage/XmlMapStorage.h
As discussed on Discord chat,
MMapper2 currently lacks a mechanism to merge two maps that are derived from the same one,
and which differ only for some (relatively minor) modifications.
A typical use case is: a player has added some information (which he may not want to share,
or may not be relevant to other players, or simply have not been integrated yet into the upstream map)
to an upstream map, but in the meantime a new upstream map was published,
and he wants to merge his personal changes into a copy of the new upstream map.
This is a classical 3-way merge, with a base map and two other maps derived from it.
MMapper2 currently has no support for such a use case, and it may contain conflicts between the two derived maps,
which may be difficult or impossible to resolve without user …
> Add feature "Export MMapper2 XML Map As..." 

- src/proxy/GmcpMessage.h
because returning them by value breaks the idiom
```C++
const std::string &str = msg.getJson()->getStdString();
```
which creates a temporary `std::optional<GmcpJson>` object, then extracts a `const std::string &` from it,
which in turn is dutifully destroyed at the `;`
> return GmcpMessage fields by const reference

- src/display/Connections.cpp
- src/mapdata/shortestpath.cpp
Faine's current map has a room connected to a non-existent room, causing a segfault in _dirs.  I don't know how that buggy connection was introduced, but this commit:
- Fixes the segfault.
- Adjusts the warning on map load so it's possible to find the bugged room.
> Fix segfault in _dirs when map has buggy connections.

- src/configuration/configuration.cpp
- src/configuration/configuration.h
- src/display/mapwindow.cpp
- src/display/mapwindow.h
- src/mainwindow/mainwindow.cpp
- src/mainwindow/mainwindow.h
Fixes #251 
Some exploratory and trivial tweaks to enable a menu option under View... for hiding the Status Bar and Scroll Bars. I just followed the general pattern of alwaysOnTop.
One conscious design decision: currently in the MainWindow constructor when it fetches the config value for alwaysOnTop, it inlines the code to manage that setting directly. I thought it made more sense to invoke the slot handler rather than copy-paste code. But eager for guidance here. 
Funny thing on naming: do we call it Scrollbars? ScrollBars? Scroll Bars? Currently in the app we say "Status Bar" but also "Toolbar". @nschimme please decide!
LMK on the debug messages I can delete them.
Also should I squash commits? Forgive my verbose commit style I haven't submitted a PR in 10 years.
> Enable hiding both status bar and scroll bars for a more minimal MapWindow

- src/CMakeLists.txt
- src/mainwindow/mainwindow.cpp
- src/mainwindow/mainwindow.h
- src/observer/gameobserver.cpp
- src/observer/gameobserver.h
- src/proxy/connectionlistener.cpp
- src/proxy/connectionlistener.h
- src/proxy/proxy.cpp
- src/proxy/proxy.h
This should be a functional no-op (no changes from player's perspective).
- As discussed in #277, introduce a `GameObserver` which brokers internal events from `Proxy`, `ConnectListener`, the `Parser`s, and `TelnetClient`s outward to downstream consumers.
- Ideally, after this change, no one should need to touch `ConnectionListener` or `Proxy` unless significantly changing how mapper communicates with the game and external client. Folks wanting to add "mud client style" windows should hopefully be saved that complexity.
- Stop passing `AutoLogger` and 'RoomManager`' instances all the way into `Proxy`.
- In `MainWindow`, port `m_Logger` and `m_roomManager` instances to use a local `m_gameObserver` instance.
- Next up, in future PRs, I will introduce a Comms window (Tells/Narrates) and …
> Game Observer (Refactoring, no-op)

- src/logger/autologger.cpp
- src/logger/autologger.h
- src/mainwindow/mainwindow.cpp
- src/observer/gameobserver.cpp
- src/observer/gameobserver.h
- src/proxy/proxy.cpp
(Hopefully minor)
@nschimme Per your feedback on the AdventureJournal PR, you requested I not duplicate the code to remove ansi in place and create a QString from Proxy-observed byte array. Here is a candidate fix submitted as its own PR for easy reviewing.
> Consolidate ANSI removal upstream

- src/adventure/adventuresession.cpp
- src/adventure/adventuresession.h
- src/adventure/lineparsers.cpp
- tests/CMakeLists.txt
- tests/testadventure.cpp
- tests/testadventure.h
Ready. I might add some more unit tests to bring code coverage up.
Basic stuff:
- Fix XP hourly rate calculation which I sadly broke at the last minute trying to do std::chrono stuff
- Add support for player kill trophy / xp
- Simple unit tests
> Adventure Panel fixes: xp hourly rate, player trophy, unit tests

- src/parser/AbstractParser-Actions.cpp
- src/parser/AbstractParser-Timer.cpp
1. Fixes bug when "Lauren" is in "stat" instead of "Gold", then timers were not shown
2. Fixes grammar bug where "_timer add simple qq" would produce text "Added simple timerqq." instead of "Added simple timer qq."
3. Fixes grammar bug where "_timer add countdown jj 299" would produce text "Added countdown timerjj for duration of 299 seconds." instead of "Added countdown timer jj for duration of 299 seconds."
> Timer bugfix

- src/clock/mumeclock.cpp
- src/clock/mumeclock.h
- src/clock/mumeclockwidget.cpp
- src/parser/abstractparser.h
- src/proxy/AbstractTelnet.cpp
- src/proxy/AbstractTelnet.h
- src/proxy/MudTelnet.cpp
- src/proxy/MudTelnet.h
- src/proxy/UserTelnet.cpp
- src/proxy/UserTelnet.h
- src/proxy/proxy.cpp
- src/proxy/proxy.h
- tests/testclock.cpp
- tests/testclock.h
Handles game time.
(Amend) Removed CMakePresets/CMakeUserPresets.
> Added Mud Server Status Protocol

- src/global/utils.h
With gcc 15 it is necessary to explicitly include <cstdint> for uint64_t.
> Add missing include for uint64_t
